apiVersion: v1
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
      <title>Dev</title>
    </head>
    <body>
      <h1>NGINX - DEV</h1>
      <p>Deployed through Kargo --> Argo CD</p>
    </body>
    </html>
kind: ConfigMap
metadata:
  name: nginx-content
